### ISSUE TITLE
Enhance routes with <template>

### ISSUE THREAD

**Issue by Malvoz** [Heydon/xiao#1]
Hello Heydon, would you consider using `<template>` elements for [routes](https://github.com/Heydon/xiao#routes)?

**Comment by Heydon** [comment]
Hi @Malvoz,

It would be possible to use `<template>` with your routes based on the current design Xiao. Let me know how you get on.

**Comment by Malvoz** [comment]
@Heydon 

I'm personally not in need of an SPA atm, but Xiao would probably be my go-to in case I would.
I just stumbled upon this project and thought I should share my thoughts.

I know you are already creating such delightful **inclusive** designs, and considering an SPA might hold multiple embeds such as `<img>` and `<iframe>` elements per route, I think it would be in both the publisher and the users interest not to load all resources for the whole SPA on every route visit. 

And [support for `<template>`](https://caniuse.com/#feat=template) is almost identical to that of [ES6](https://caniuse.com/#search=es6).

Cheers!

**Comment by Heydon** [comment]
@Malvoz,

Absolutely agree! But you can already hook into route changes to compile templates, etc. Routes can have static content, sent from the server, or fetch/compile stuff as you wish. Depends what you build on top of it. Hope that helps.
